### PR TITLE
Apply sigmoid before calc dice in eval_net()

### PR DESCRIPTION
**Pull request by whenyd**
1. Apply `sigmoid` before calc dice.
2. The for loop is unnecessary, result of `dice_coeff` is just batch mean.
3. Keyword `unit` and `total` of progress bar are modified.

### CODE REVIEW

**Comment by milesial** [comment]
Thanks, looks good!
Just one thing, I don't know if changing the granularity from images to batches is good.
The average of the batch mean is different than the normal average when the last batch is not the same size as the other batches (when the batch size does not divide the number of images).
Going back to the per-image processing would be more accurate for large batch sizes.

**Comment by whenyd** [comment]
Yes, it's a problem. But the difference is very small when dataset is big enough, anyway,  we can drop the last batch by set `drop_last=True` to get accurate result.

**Comment by milesial** [comment]
I guess we can accept this solution to get a cleaner code. This may be a problem for people with small dataset and large batch size, but they are not very common.

However, the drop_last should be on the val loader, not the train loader :)

**Comment by whenyd** [comment]
oh yes, maybe my hands are out of control at that moment, I've correct this fault.

**Comment by milesial** [comment]
Thanks for your contribution! I'm merging this.

**Pull request merged**
