### PR TITLE
W&B: Add wandb login prompt with timeout

### PR DESCRIPTION
**Pull request by AyushExel**
This PR:
* ### Adds support for wandb login prompt with a timeout.
 The prompt shows up only if you're not already logged in.
**Case 1: When you're already logged in:**
    (This will directly start logging in your wandb account)
Screenshot from 2021-10-19 03-14-21
**Case 2: When you're not logged in and login times out**
(this will log anonymode runs)
Screenshot from 2021-10-19 03-31-15

### CODE REVIEW

**Comment by AyushExel** [comment]
@milesial can you have a look at this? This will work with existing code. The advantage is that the non-anymode runs are never deleted unlike unclaimed anonymous runs.

**Comment by milesial** [comment]
I don't get this issue that this is solving. If you don't want anonymous runs, just set the `WANDB_API_KEY` env variable, no?

**Comment by AyushExel** [comment]
@milesial yeah that works as well but it's a manual effort. this prompt was built to be more user-friendly without stalling the training for more than 30secs. If no input is provided it'll switch to anonymous mode again.

**Comment by milesial** [comment]
Looking at it from the point of view of a new user who doesn't have a W&B account but still wants the nice logging, this still feels strange to me. If there was a 4th option to run in anonymous mode, it would be nice. Right now, new users have to either wait 30s, which is a long time, or choose (3), which turns off the plots.

**Comment by AyushExel** [comment]
@milesial yes fair point. Let me see if I can change it based on your feedback. This is very useful, thanks!

**Comment by AyushExel** [comment]
@milesial Hey, Instead of adding this PR feature, can you please add in the "W&B section" in the readme that "Unclaimed anonymous runs are automatically deleted after 7 days"? There is a similar banner on the anonymous runs in the UI but It'd be nice if the users know it beforehand.

**Comment by AyushExel** [comment]
Hey!  thanks. closing this now

**Pull request closed without merging**
